BIN = ./bin
SRC = ./src
OBJ = ./obj
INC = ./inc

CC = clang
CFLAGS = -Wall -Wextra --pedantic-errors -O3 -g


1 : $(BIN)/1.out

$(BIN)/1.out : $(SRC)/1.c
	$(CC) $(CFLAGS) $< -o $@

2 : $(BIN)/2.out

$(BIN)/2.out : $(SRC)/2.c
	$(CC) $(CFLAGS) $< -o $@

3 : $(BIN)/3.out

$(BIN)/3.out : $(SRC)/3.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

4 : $(BIN)/4.out

$(BIN)/4.out : $(SRC)/4.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

5 : $(BIN)/5.out

$(BIN)/5.out : $(SRC)/5.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

6 : $(BIN)/6.out

$(BIN)/6.out : $(SRC)/6.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

7 : $(BIN)/7.out

$(BIN)/7.out : $(SRC)/7.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

8 : $(BIN)/8.out

$(BIN)/8.out : $(SRC)/8.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

11 : $(BIN)/11.out

$(BIN)/11.out : $(SRC)/11.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

13 : $(BIN)/13.out

$(BIN)/13.out : $(SRC)/13.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

15 : $(BIN)/15.out

$(BIN)/15.out : $(SRC)/15.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

16 : $(BIN)/16.out

$(BIN)/16.out : $(SRC)/16.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

17 : $(BIN)/17.out

$(BIN)/17.out : $(SRC)/17.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

20 : $(BIN)/20.out

$(BIN)/20.out : $(SRC)/20.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

21 : $(BIN)/21.out

$(BIN)/21.out : $(SRC)/21.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

28 : $(BIN)/28.out

$(BIN)/28.out : $(SRC)/28.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

30 : $(BIN)/30.out

$(BIN)/30.out : $(SRC)/30.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

41 : $(BIN)/41.out

$(BIN)/41.out : $(SRC)/41.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

43 : $(BIN)/43.out

$(BIN)/43.out : $(SRC)/43.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

48 : $(BIN)/48.out

$(BIN)/48.out : $(SRC)/48.c
	$(CC) $(CFLAGS) -I $(INC) $< -o $@

clean : 
	rm -f $(BIN)/* $(OBJ)/*
	