#ifndef NUM_FRAMES_PER_GAME
#define NUM_FRAMES_PER_GAME 10
#endif

#ifndef END_FRAME_PADDING
#define END_FRAME_PADDING 2
#endif
#ifndef TOTAL_SIZE
#define TOTAL_SIZE NUM_FRAMES_PER_GAME + END_FRAME_PADDING
#endif

#ifndef NUM_THROWS_PER_FRAME
#define NUM_THROWS_PER_FRAME 2
#endif

#ifndef PINS_PER_FRAME
#define PINS_PER_FRAME 10
#endif